### ISSUE TITLE
New files and folders are not respected

### ISSUE THREAD

**Issue by taukakao** [linux-immutability-tools/EtcBuilder#1] opened 2024-04-08 18:11 UTC
If the user creates a new file, EtcBuilder will ignore it. 

This is causing this issue downstream https://github.com/Vanilla-OS/ABRoot/issues/247

**Comment by taukakao** [comment] 2024-04-13 17:40
@axtloss 
Issue persists in newest version. 
For some reason, the condition here never returns true so the userPaths slice stays empty.
https://github.com/linux-immutability-tools/EtcBuilder/blob/82dff2a0db8fc6922b2abe6fb6e84335cb09c17a/cmd/build.go#L207C6-L207C22

**Comment by axtloss** [comment] 2024-04-13 19:30
https://github.com/taukakao/ABRoot/blob/14a58e59dc49c3b03e2e034ba8a93385dc95f85a/go.mod#L186

why aren't you using upstream etcbuilder

**Comment by taukakao** [comment] 2024-04-13 19:53
@axtloss 

For more logs. I also tried with the  upsteam version:
https://github.com/taukakao/ABRoot/actions/runs/8674865913

**Comment by axtloss** [comment] 2024-04-13 20:54
I am unable to reproduce the issue with etcbuilder.
Appropriate logs would be helpful

**Comment by taukakao** [comment] 2024-04-13 21:26
I will provide the logs when I get the chance but they are not that exciting. 
It's just copying the files that exist in the future sys and the userPaths directory stays empty. 

Also note that the command differs from the API implementation in this line, which will mark pretty much every file as not in sys:
https://github.com/linux-immutability-tools/EtcBuilder/blob/82dff2a0db8fc6922b2abe6fb6e84335cb09c17a/cmd/build.go#L152

**Comment by axtloss** [comment] 2024-04-13 23:57
Fixed in https://github.com/linux-immutability-tools/EtcBuilder/commit/d438ca08aa42634a10da240bbdee0f0ab25a5348

**Closed as completed by axtloss** 2024-04-13 23:57 UTC
